### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by LauraTink** [abeleuta/easyannotation#30]
Within the AnnotationContainer config options, it would be useful to be able to set the blur radius, along with the option to set the text colour separately to the fill colour. At the moment the text colour is the same as the fill settings.

**Comment by abeleuta** [comment]
Hello,

Thank you for suggestions. Blur radius is available now as an option and also each annotator can be individually configured during initialization.

Text color can be set using fillStyle. This is because text can be configured to have blurring or shadows as other fill options, so then same configuration is used.
